/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservaarmamento;

import reservaarmamento.conexao.Conexao;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author glaucia
 */
public class CadastrarMaterial extends javax.swing.JFrame {

    Conexao con_cad_mat;

    /**
     * Creates new form CadastrarMaterial
     */
    public CadastrarMaterial() {

        this.setExtendedState(MAXIMIZED_BOTH);

        con_cad_mat = new Conexao();
        con_cad_mat.conecta();
        con_cad_mat.executeSQL("select * from material");

        initComponents();
        listarCodigo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salvar = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        codMat = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        nomeMat = new UpperCaseField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        modMat = new UpperCaseField();
        sitMat = new UpperCaseField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        obs = new UpperCaseField();
        marcaMat = new UpperCaseField();
        numSerie = new UpperCaseField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        calibre = new UpperCaseField();
        numPat = new UpperCaseField();
        qtdMat = new UpperCaseField();
        tombo = new UpperCaseField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRAR NOVO MATERIAL");
        setPreferredSize(new java.awt.Dimension(1165, 621));
        setResizable(false);

        Salvar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/icones/salvar.png"))); // NOI18N
        Salvar.setText("SALVAR");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        Sair.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/icones/fechar.png"))); // NOI18N
        Sair.setText("SAIR");
        Sair.setPreferredSize(new java.awt.Dimension(99, 33));
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição do Material", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("COD. MATERIAL:");

        codMat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        codMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codMatActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("NOME MATERIAL:");

        nomeMat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nomeMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeMatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("SITUAÇÃO:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("MODELO :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("TOMBO:");

        modMat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        sitMat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sitMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitMatActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("QUANTIDADE:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("NÚMERO SÉRIE:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("MARCA :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("OBSERVAÇÃO:");

        obs.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        marcaMat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        numSerie.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("NÚMERO PATRIMÔNIO:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("CALIBRE :");

        calibre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        numPat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        qtdMat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeMat, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codMat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modMat, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sitMat, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tombo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numSerie))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(obs))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(qtdMat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(marcaMat)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(calibre))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(numPat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(39, 56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(numSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sitMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(qtdMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(numPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(marcaMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(calibre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jComboBox2.getAccessibleContext().setAccessibleName("");
        jComboBox2.getAccessibleContext().setAccessibleDescription("Cadastro existente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(Salvar)
                        .addGap(41, 41, 41)
                        .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salvar))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    public void listarCodigo() {

        PreparedStatement cnd;
        try {
            cnd = con_cad_mat.conecta().prepareStatement("select * from tipo_material");
            ResultSet rs;
            rs = cnd.executeQuery();
            //int i = 0;
            //String tipo[] = {};
            while (rs.next()) {
                //JOptionPane.showMessageDialog(null, ""+rs.getString("descricao_material"));
                //tipo[i] = rs.getString("codigo_tipo_material");
                jComboBox2.addItem(rs.getString("codigo_tipo_material") + "  " + rs.getString("descricao_material"));
                //i++;
            }
            jComboBox2.addItem("Novo");
        } catch (Exception e) {
        }
    }
    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        // TODO add your handling code here:
        if (nomeMat.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Preencha o campo Nome!!!", "Campo Vazio", JOptionPane.INFORMATION_MESSAGE);
            nomeMat.requestFocus();

        } else if (qtdMat.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Preencha o campo quantidade de material !!!", "Campo Vazio", JOptionPane.INFORMATION_MESSAGE);
            qtdMat.requestFocus();
        } else if (sitMat.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Preencha o campo situação do material !!!", "Campo Vazio", JOptionPane.INFORMATION_MESSAGE);
            sitMat.requestFocus();
        } else {
            try {
                String sql = "insert into material (tipo_material_codigo_tipo_material,"
                        + "nome_material,"
                        + "qtde_material,"
                        + "situacao_material,"
                        + "numero_material,"
                        + "numero_patrimonio_material,"
                        + "marca_material,"
                        + "modelo_material,"
                        + "calibre_material,"
                        + "numero_tombo_material,"
                        + "observacao) values ('" + codMat.getText() + "',"
                        + "'" + nomeMat.getText() + "',"
                        + "'" + qtdMat.getText() + "',"
                        + "'" + sitMat.getText() + "',"
                        + "'" + numSerie.getText() + "',"
                        + "'" + numPat.getText() + "',"
                        + "'" + marcaMat.getText() + "',"
                        + "'" + modMat.getText() + "',"
                        + "'" + calibre.getText() + "',"
                        + "'" + tombo.getText() + "',"
                        + "'" + obs.getText() + "');";

                con_cad_mat.statement.executeUpdate(sql);

                PreparedStatement cnd;
                try {
                    cnd = con_cad_mat.conecta().prepareStatement("select * from tipo_material");
                    ResultSet rs;
                    rs = cnd.executeQuery();
                    int qtd = 0;
                    int procura = 0;
                    while (rs.next()) {

                        if (codMat.getText().toString().equals(rs.getString("codigo_tipo_material"))) {
                            procura = 1;
                            if (procura == 1) {
                                qtd = Integer.parseInt(rs.getString("quantidade_material"));
                                qtd = qtd + Integer.parseInt(qtdMat.getText().toString());
                                try {
                                    String sql3 = "UPDATE tipo_material SET quantidade_material= ?  WHERE codigo_tipo_material = " + codMat.getText().toString() + " ";
                                    PreparedStatement cnd2;

                                    cnd2 = con_cad_mat.conecta().prepareStatement(sql3);
                                    cnd2.setInt(1, qtd);

                                    cnd2.executeUpdate();
                                    JOptionPane.showMessageDialog(null, "Dados atualizado com sucesso!");

                                } catch (SQLException erro) {
                                    JOptionPane.showMessageDialog(null, erro);
                                }
                            }
                        }
                        procura = 0;
                    }
                    if (qtd == 0) {
                        String sql4 = "insert into tipo_material (descricao_material,"
                                + "quantidade_material)"
                                + "values ('" + nomeMat.getText() + "'," + Integer.parseInt(qtdMat.getText().toString()) + ");";

                        con_cad_mat.statement.executeUpdate(sql4);
                    }

                } catch (Exception e) {
                }

                JOptionPane.showMessageDialog(null, "Cadastro realizada com sucesso");
                //    dispose();

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "houve um erro:" + erro);
                //      dispose(); 
            }
        }
        limparCampos();
    }//GEN-LAST:event_SalvarActionPerformed

    public void limparCampos() {
        nomeMat.setText("");
        qtdMat.setText("");
        sitMat.setText("");
        numSerie.setText("");
        numPat.setText("");
        modMat.setText("");
        marcaMat.setText("");
        calibre.setText("");
        tombo.setText("");
        obs.setText("");
    }

    private void sitMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitMatActionPerformed

    private void nomeMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeMatActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, ""+jComboBox2.getSelectedIndex());
        String codigo = (String) jComboBox2.getSelectedItem();
        if (!codigo.equals("Novo")) {
            codMat.setText("" + codigo.charAt(0));
            codMat.setEditable(false);
            nomeMat.setText(""+ codigo.substring(2, codigo.length()));
        } else {
            PreparedStatement cnd3;
            try {
                cnd3 = con_cad_mat.conecta().prepareStatement("select COUNT(codigo_tipo_material) as maximo from tipo_material");
                ResultSet rs3;
                rs3 = cnd3.executeQuery();

                int qtd = 0;
                while (rs3.next()) {
                    qtd = Integer.parseInt(rs3.getString("maximo"));
                }
                codMat.setText("" + (qtd + 1));
                codMat.setEditable(false);
                nomeMat.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "" + e);
            }

        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void codMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codMatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JButton Salvar;
    private javax.swing.JTextField calibre;
    private javax.swing.JTextField codMat;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField marcaMat;
    private javax.swing.JTextField modMat;
    private javax.swing.JTextField nomeMat;
    private javax.swing.JTextField numPat;
    private javax.swing.JTextField numSerie;
    private javax.swing.JTextField obs;
    private javax.swing.JTextField qtdMat;
    private javax.swing.JTextField sitMat;
    private javax.swing.JTextField tombo;
    // End of variables declaration//GEN-END:variables
}
